### ISSUE TITLE
Create event fields

### ISSUE THREAD

**Issue by shamintehrani** [ramp106/global_event_technology_api_client#2]
### User Story
As OMR I want to create event fields for Masterclasses and Guided Tours so all accepted attendees can get access at the festival with their chip.

### Acceptance Criteria

- [x] create MC fields based on GET access data
- [x] create GT fields based on GET access data
- [ ] assign fields to according tickets (accepted applicants)
- [x] create areas for MCs/GTs on GETs side
- [ ] assign the according MC fields to accepted attendees

### Screenshot
here is an example from OMR23
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHNlQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a57b0c8b4422018b3e248354c56adf72d3165a6e/image.png)

**Comment by svenf1105** [comment]
@shamintehrani we also need to create the areas for the masterclasses on GETs side

**Comment by shamintehrani** [comment]
everything else will be done within this ticket: https://app.zenhub.com/workspaces/omr-development---event-management-b2b-633adfeb410e2256aaa6959a/issues/gh/ramp106/myomr/5825
